import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.wrapper}>
          <div className={styles.sheet}>
            {/* Top of the website */}
              <div className={styles.top}>
                <div className={styles.SheetTop}>
                  Top of the page
                  <div>
                    Character name
                  </div>
                  <div>
                    Class&level, background, playername, race, aligment, experience points.
                  </div>
                </div>
              </div>
            {/* First Column */}
              <div className={styles.leftSide}>
                <div className={styles.leftStatsContainer}>
                  <div className={styles.attributesContainer}>
                    <div>Strength</div>
                    <div>Value</div>
                    <div>Score</div>
                    </div>
                  <div className={styles.attributesContainer}>
                    <div>Dexterity</div>
                    <div>Value</div>
                    <div>Score</div>
                  </div>
                  <div className={styles.attributesContainer}>
                    <div>Constitution</div>
                    <div>Value</div>
                    <div>Score</div>
                  </div>
                  <div className={styles.attributesContainer}>
                    <div>Inteligence</div>
                    <div>Value</div>
                    <div>Score</div>
                  </div>
                  <div className={styles.attributesContainer}>
                    <div>Wisdom</div>
                    <div>Value</div>
                    <div>Score</div>
                  </div>
                  <div className={styles.attributesContainer}>
                    <div>Charisma</div>
                    <div>Value</div>
                    <div>Score</div>
                  </div>
                </div>
                <div className={styles.rightStatsContainer}>
                  <div>
                    <input type="checkbox" name="inspiration_proff_check"/>
                    Inspiration
                  </div>
                  <div>
                    <span> value </span>
                    <span>ProficiencyBonus</span>
                  </div>
                  <div>
                    <div className={styles.describingTextSize}>
                      <input type="checkbox" name="ability_st_proff_check" id="" />
                      <span>Value </span>
                      <span>Strength</span>
                    </div>
                    <div className={styles.describingTextSize}>
                      <input type="checkbox" name="ability_st_proff_check" id="" />
                      <span>Value </span>
                      <span>Dexterity</span>
                    </div>
                    <div className={styles.describingTextSize}>
                      <input type="checkbox" name="ability_st_proff_check" id="" />
                      <span>Value </span>
                      <span>Constitution</span>
                    </div>
                    <div className={styles.describingTextSize}>
                      <input type="checkbox" name="ability_st_proff_check" id="" />
                      <span>Value </span>
                      <span>Intelligence</span>
                    </div>
                    <div className={styles.describingTextSize}>
                      <input type="checkbox" name="ability_st_proff_check" id="" />
                      <span>Value </span>
                      <span>Wisdom</span>
                    </div>
                    <div className={styles.describingTextSize}>
                      <input type="checkbox" name="ability_st_proff_check" id="" />
                      <span>Value </span>
                      <span>Strength</span>
                    </div>
                    <div>Saving Throws</div>
                  </div>
                  <div className={styles.describingTextSize}> {/*Skills */}
                    <div>
                      <input type="checkbox" name="skill_checkbox" />
                      <span>value </span>
                      <span>Acrobatics</span>
                    </div>
                    <div>
                      <input type="checkbox" name="skill_checkbox" />
                      <span>value </span>
                      <span>Animal Handling</span>
                    </div>
                    <div>
                      <input type="checkbox" name="skill_checkbox" />
                      <span>value </span>
                      <span>Arcana</span>
                    </div>
                    <div>
                      <input type="checkbox" name="skill_checkbox" />
                      <span>value </span>
                      <span>Athletics</span>
                      </div>
                    <div>
                      <input type="checkbox" name="skill_checkbox" />
                      <span>value </span>
                      <span>Deception</span>
                    </div>
                    <div>
                      <input type="checkbox" name="skill_checkbox" />
                      <span>value </span>
                      <span>History</span>
                    </div>
                    <div>
                      <input type="checkbox" name="skill_checkbox" />
                      <span>value </span>
                      <span>Insight</span>
                    </div>
                    <div>
                      <input type="checkbox" name="skill_checkbox" />
                      <span>value </span>
                      <span>Intimidation</span>
                    </div>
                    <div>
                      <input type="checkbox" name="skill_checkbox" />
                      <span>value </span>
                      <span>Investigation</span>
                    </div>
                    <div>
                      <input type="checkbox" name="skill_checkbox" />
                      <span>value </span>
                      <span>Medicine</span>
                    </div>
                    <div>
                      <input type="checkbox" name="skill_checkbox" />
                      <span>value </span>
                      <span>Nature</span>
                    </div>
                    <div>
                      <input type="checkbox" name="skill_checkbox" />
                      <span>value </span>
                      <span>Perception</span>
                    </div>
                    <div>
                      <input type="checkbox" name="skill_checkbox" />
                      <span>value </span>
                      <span>Performance</span>
                    </div>
                    <div>
                      <input type="checkbox" name="skill_checkbox" />
                      <span>value </span>
                      <span>Persuasion</span>
                    </div>
                    <div>
                      <input type="checkbox" name="skill_checkbox" />
                      <span>value </span>
                      <span>Religion</span>
                    </div>
                    <div>
                      <input type="checkbox" name="skill_checkbox" />
                      <span>value </span>
                      <span>Sleight of Hands</span>
                    </div>
                    <div>
                      <input type="checkbox" name="skill_checkbox" />
                      <span>value </span>
                      <span>Stealth</span>
                    </div>
                    <div>
                      <input type="checkbox" name="skill_checkbox" />
                      <span>value </span>
                      <span>Survival</span>
                    </div>
                  </div>
                </div>
                <div className={styles.lowerStatsContainer}>
                    <div>
                      <span>Value </span>
                      Passive Wisdom
                    </div>
                    <div>
                      Other Proficiencies & Languages
                      <input type="text"></input>
                    </div>
                </div>
              </div>
            {/* Second Column */}
              <div className={styles.middleSide}>
                <div className={styles.combatSpecific}> {/* Combat stuff */}
                  <div className={`${styles.armorClassBox} ${styles.combatBoxOrder}`}>
                    <input type="text" name="" className={styles.centerInput} />
                    <div className={styles.centerLabel}>ARMOR CLASS</div>
                  </div>
                  <div className={`${styles.initativeBox} ${styles.combatBoxOrder}`}>
                    <input type="text" name="" className={styles.centerInput} />
                    <div className={styles.centerLabel}>INIATIVE</div>
                  </div>
                  <div className={`${styles.speedBox} ${styles.combatBoxOrder}`}>
                    <input type="text" name="" className={styles.centerInput} />
                    <div className={styles.centerLabel}>SPEED</div>
                  </div>
                  <div className={styles.currentHPBox}>
                    Current Hit Points
                  </div>
                  <div className={styles.temporaryHPBox}>
                    Temporary Hit Points
                  </div>
                  <div className={styles.hitDiceBox}>
                    Hit Dice
                  </div>
                  <div className={styles.deathSavesBox}>
                    Death Saves
                  </div>
                </div>
                <div> {/* Attack & spell casting  */}
                <p>
                  <textarea rows="4" cols="50" name="comment" form="usrform"></textarea>
                  </p>
                <span>Attack & Spellcasting</span>
                </div>
                <div> {/* EQ */}
                <p>
                <textarea rows="4" cols="50" name="comment" form="usrform"></textarea>
                </p>
                <span>Equipment</span>
                </div>
              </div>
            {/* Third Column */}
              <div className={styles.rightSide}>
                <div>
                  <textarea rows="2" cols="30" name="comment" form="usrform"></textarea>
                  <label>Personality traits </label>
                </div>
                <div>
                  <textarea rows="2" cols="30" name="comment" form="usrform"></textarea>
                  <label className={styles.center}>Ideas</label> 
                </div>
                <div>
                  <textarea  tarea rows="2" cols="30" name="comment" form="usrform"></textarea>
                  <label>Bonds</label> 
                </div>
                <div>
                  <textarea rows="2" cols="30" name="comment" form="usrform"></textarea>
                  <label>Flaws</label> 
                </div>
                <div> {/*Freatures */}
                  Features
                </div>
              </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
